const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {
    try {
        const user = await prisma.user.findFirst()
        if (!user) {
            console.log("No user found to attach subject to.")
            return
        }
        console.log("Found user:", user.email)

        const subject = await prisma.subject.create({
            data: {
                title: "Test Physics",
                description: "Generated by diagnostics",
                userId: user.id
            }
        })
        console.log("Created subject:", subject.title)

    } catch (e) {
        console.error('Write Error:', e)
    } finally {
        await prisma.$disconnect()
    }
}

main()
